title: blog
description: Een eenvoudige Jekyll blog

# Build settings
markdown: kramdown

# Defaults
defaults:
  - scope:
      path: ""
    values:
      layout: "default"

      # Collections
collections:
  pages:
    output: true
    permalink: /:collection/:name.html
    layout: page
